services:
  api:
    image: "marquez:0.50.0_custom"
    container_name: marquez-api
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./marquez_data:/opt/marquez

  web:
    image: "marquez-web:0.50.0_custom"
    container_name: marquez-web
    environment:
      - MARQUEZ_HOST=api
      - MARQUEZ_PORT=5000
      - WEB_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - api
