version: "3.7"
services:
  opensearch:
    image: opensearchproject/opensearch:2.17.0
    container_name: marquez-search
    hostname: opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - plugins.security.ssl.http.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=XXXXXXXXXXXXXX
    volumes:
      - ./opensearch_data:/usr/share/opensearch/data
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"

