version: '3.8'
services:
  postgres:
    image: 'postgres:15.2'
    restart: unless-stopped
    volumes:
     - './postgres_data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_PASSWORD='XXXXXXXXXXXXXX'
    ports:
    - '5432:5432'
